# Generated by Django 4.2.7 on 2025-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='air_quality_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='cloud_coverage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='dew_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='uv_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='visibility',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_gust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Tashkent', max_length=100)),
                ('forecast_date', models.DateField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_day', models.FloatField()),
                ('temp_night', models.FloatField()),
                ('feels_like_day', models.FloatField(blank=True, null=True)),
                ('feels_like_night', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.CharField(max_length=20)),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(default=0)),
                ('precipitation_probability', models.IntegerField(default=0)),
                ('weather_condition', models.CharField(max_length=100)),
                ('weather_description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=10)),
                ('cloud_coverage', models.IntegerField(default=0)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(default=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('location', 'forecast_date')},
            },
        ),
    ]
