# Generated by Django 4.2.7 on 2025-08-07 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('area_sqm', models.FloatField()),
                ('plant_count', models.IntegerField(default=0)),
                ('soil_type', models.CharField(default='loam', max_length=50)),
                ('default_duration_minutes', models.IntegerField(default=15)),
                ('flow_rate_lpm', models.FloatField(default=10)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('maintenance', "Ta'mirlash"), ('error', 'Xato')], default='active', max_length=20)),
                ('last_irrigated', models.DateTimeField(blank=True, null=True)),
                ('total_water_used_l', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('planted_date', models.DateField()),
                ('growth_stage', models.CharField(choices=[('seed', "Urug'"), ('germination', 'Unish'), ('seedling', "Ko'chat"), ('vegetative', "Vegetativ o'sish"), ('flowering', 'Gullash'), ('fruiting', 'Mevali'), ('mature', 'Pishgan')], default='seed', max_length=20)),
                ('health_status', models.CharField(choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('fair', "O'rtacha"), ('poor', 'Yomon'), ('critical', 'Kritik')], default='good', max_length=20)),
                ('height', models.FloatField(blank=True, null=True)),
                ('leaf_count', models.IntegerField(blank=True, null=True)),
                ('fruit_count', models.IntegerField(blank=True, null=True)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('water_amount_ml', models.IntegerField(default=0)),
                ('last_fertilized', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🌱', max_length=10)),
                ('optimal_soil_moisture_min', models.FloatField(default=60)),
                ('optimal_soil_moisture_max', models.FloatField(default=80)),
                ('optimal_temperature_min', models.FloatField(default=18)),
                ('optimal_temperature_max', models.FloatField(default=25)),
                ('optimal_ph_min', models.FloatField(default=6.0)),
                ('optimal_ph_max', models.FloatField(default=7.0)),
                ('germination_days', models.IntegerField(default=7)),
                ('vegetative_days', models.IntegerField(default=30)),
                ('flowering_days', models.IntegerField(default=60)),
                ('maturity_days', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='PlantCareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('watering', "Sug'orish"), ('fertilizing', "O'g'itlash"), ('pruning', 'Kesish'), ('pesticide', 'Zararkunandalarga qarshi'), ('transplanting', "Ko'chirish"), ('observation', 'Kuzatish')], max_length=20)),
                ('description', models.TextField()),
                ('care_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('water_amount_ml', models.IntegerField(blank=True, null=True)),
                ('fertilizer_type', models.CharField(blank=True, max_length=100)),
                ('fertilizer_amount_g', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='plant.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.planttype'),
        ),
        migrations.CreateModel(
            name='IrrigationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('automatic', 'Avtomatik'), ('manual', "Qo'lda"), ('scheduled', 'Rejalashtirilgan'), ('emergency', 'Favqulodda')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('failed', 'Muvaffaqiyatsiz')], default='scheduled', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField()),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('water_amount_ml', models.IntegerField()),
                ('actual_water_amount_ml', models.IntegerField(blank=True, null=True)),
                ('trigger_reason', models.TextField()),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_events', to='plant.plant')),
            ],
        ),
    ]
